package `in`.ankitsaroj.diable.navigation

object Routes {
    const val Home = "home"
    const val Search = "search"
    const val DiableSettings = "diable_settings"
    const val Productivity = "productivity"
    const val Advanced = "advanced"
    const val Themes = "themes"
    const val ChooseWallpaper = "choose_wallpaper"
    const val ThemeEditor = "theme_editor"
    const val ThemeCarousel = "theme_carousel"
    const val ClockStyle = "clock_style"
    const val SelectWidget = "select_widget"
    const val EditFavorites = "edit_favorites"
    const val HideApps = "hide_apps"
    const val Folders = "folders"
    const val MusicApps = "music_apps"
    const val CalendarAgenda = "calendar_agenda"
    const val Changelog = "changelog"
    const val DiablePro = "diable_pro"
    const val HelpFeedback = "help_feedback"
    const val Community = "community"
    const val CreateTheme = "create_theme"
    const val EditTheme = "edit_theme"
    const val MyThemes = "my_themes"
    const val ReadyMadeThemes = "ready_made_themes"
    const val CommunityThemes = "community_themes"
}
